//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimbiricheDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bans
    {
        public int idBan { get; set; }
        public Nullable<int> idBannedPlayer { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
