//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimbiricheDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerColors
    {
        public int idPlayerColors { get; set; }
        public Nullable<int> idPlayer { get; set; }
        public Nullable<int> idColor { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Players Players { get; set; }
    }
}
