//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimbiricheDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int idReport { get; set; }
        public Nullable<int> idPlayerReported { get; set; }
        public Nullable<int> idPlayerReporter { get; set; }
        public Nullable<System.DateTime> reportDate { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
